services:
  kafka:
    image: "apache/kafka:${KAFKA_VERSION}"
    hostname: kafka-standalone
    container_name: kafka-standalone
    ports:
      - '9092:9092'
    environment:
      # Ref: https://github.com/apache/kafka/blob/3.9.0/docker/examples/docker-compose-files/single-node/plaintext/docker-compose.yml
      # Most of these are default values from config/kraft/server.properties. We only want to tweak the listeners
      # But we need to set all the other properties as well for the broker/controller to work as expected.
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka-standalone:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-standalone:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # MISC
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - "$HOST_KAFKA_DIR/data:/tmp"
      - "$HOST_KAFKA_DIR/out:/out"
    networks:
      - kafka

networks:
  kafka:
