spring:
  application:
    name: playground-kafka

management:
  endpoints:
    web:
      # Change /actuator endpoints to /. (e.g. /actuator/health -> /health)
      base-path: /

logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        security: INFO
